# **Statistical analysis**

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("/content/drive/MyDrive/ML and DL DataSets/End_to_End_Financial_Fraud_Anomaly_Detection/Financial_Fraud_Dataset.csv")

In [ ]:
#1. print the shape of the data
df.shape

(6362620, 11)

In [ ]:
#2. printing the information of the data
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6362620 entries, 0 to 6362619
Data columns (total 11 columns):
 #   Column          Dtype
---  ------          -----
 0   step            int64
 1   type            object
 2   amount          float64
 3   nameOrig        object
 4   oldbalanceOrg   float64
 5   newbalanceOrig  float64
 6   nameDest        object
 7   oldbalanceDest  float64
 8   newbalanceDest  float64
 9   isFraud         int64
 10  isFlaggedFraud  int64
dtypes: float64(5), int64(3), object(3)
memory usage: 534.0+ MB

**The columns include:**
1. **step:** An integer representing the time step of the transaction.
2. **type:** Categorical variable indicating the type of transaction.
3. **amount:** Float value representing the amount of the transaction.
4. **nameOrig:** Object type representing the name of the origin account.
5. **oldbalanceOrg:** Float value indicating the old balance of the origin account before the transaction.
6. **newbalanceOrig:** Float value indicating the new balance of the origin account after the transaction.
7. **nameDest:** Object type representing the name of the destination account.
8. **oldbalanceDest:** Float value indicating the old balance of the destination account before the transaction.
9. **newbalanceDest:** Float value indicating the new balance of the destination account after the transaction.
10. **isFraud:** Binary integer indicating whether the transaction is fraudulent (1) or not (0).
11. **isFlaggedFraud:** Binary integer indicating whether the transaction was flagged as fraudulent (1) or not (0)

In [ ]:
#3. describing the data
df.describe()

,step,amount,oldbalanceOrg,newbalanceOrig,oldbalanceDest,newbalanceDest,isFraud,isFlaggedFraud
count,6.362620e+06,6.362620e+06,6.362620e+06,6.362620e+06,6.362620e+06,6.362620e+06,6.362620e+06,6.362620e+06
mean,2.433972e+02,1.798619e+05,8.338831e+05,8.551137e+05,1.100702e+06,1.224996e+06,1.290820e-03,2.514687e-06
std,1.423320e+02,6.038582e+05,2.888243e+06,2.924049e+06,3.399180e+06,3.674129e+06,3.590480e-02,1.585775e-03
min,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,1.560000e+02,1.338957e+04,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
50%,2.390000e+02,7.487194e+04,1.420800e+04,0.000000e+00,1.327057e+05,2.146614e+05,0.000000e+00,0.000000e+00
75%,3.350000e+02,2.087215e+05,1.073152e+05,1.442584e+05,9.430367e+05,1.111909e+06,0.000000e+00,0.000000e+00
max,7.430000e+02,9.244552e+07,5.958504e+07,4.958504e+07,3.560159e+08,3.561793e+08,1.000000e+00,1.000000e+00

In [ ]:
#4. checking the missing values in the data
df.isnull().sum()

step              0
type              0
amount            0
nameOrig          0
oldbalanceOrg     0
newbalanceOrig    0
nameDest          0
oldbalanceDest    0
newbalanceDest    0
isFraud           0
isFlaggedFraud    0
dtype: int64

In [ ]:
#5. Value Counts for Categorical Variables
print("\nValue Counts for Categorical Variables:")
print(df['type'].value_counts())
print(df['isFraud'].value_counts())
print(df['isFlaggedFraud'].value_counts())

Value Counts for Categorical Variables:
type
CASH_OUT    2237500
PAYMENT     2151495
CASH_IN     1399284
TRANSFER     532909
DEBIT         41432
Name: count, dtype: int64
isFraud
0    6354407
1       8213
Name: count, dtype: int64
isFlaggedFraud
0    6362604
1         16
Name: count, dtype: int64

In [ ]:
#6. Flagged Fraud analysis
flagged_fraud_counts = df['isFlaggedFraud'].value_counts()
print("\nFlagged Fraud Counts:")
print(flagged_fraud_counts)

Flagged Fraud Counts:
isFlaggedFraud
0    6362604
1         16
Name: count, dtype: int64

In [ ]:
#7 printing unique values counts for each column
for col in df.columns:
    print(f"Unique values for column {col}")
    print(df[col].value_counts())
    print("======================================================")

Unique values for column step
step
19     51352
18     49579
187    49083
235    47491
307    46968
       ...
706        4
721        4
693        4
112        2
662        2
Name: count, Length: 743, dtype: int64
======================================================
Unique values for column type
type
CASH_OUT    2237500
PAYMENT     2151495
CASH_IN     1399284
TRANSFER     532909
DEBIT         41432
Name: count, dtype: int64
======================================================
Unique values for column amount
amount
10000000.00    3207
10000.00         88
5000.00          79
15000.00         68
500.00           65
               ...
151849.59         1
341252.72         1
431409.04         1
344148.22         1
258347.61         1
Name: count, Length: 5316900, dtype: int64
======================================================
Unique values for column nameOrig
nameOrig
C1530544995    3
C545315117     3
C724452879     3
C1784010646    3
C1677795071    3
              ..
C1567523029    1
C644777639     1
C1256645416    1
C1231536757    1
C1971151096    1
Name: count, Length: 6353307, dtype: int64
======================================================
Unique values for column oldbalanceOrg
oldbalanceOrg
0.00         2102449
184.00           918
133.00           914
195.00           912
164.00           909
              ...
533881.37          1
288393.93          1
249266.97          1
247085.71          1
485988.55          1
Name: count, Length: 1845844, dtype: int64
======================================================
Unique values for column newbalanceOrig
newbalanceOrig
0.00         3609566
7468.59            4
45633.24           4
7802.01            4
16828.17           4
              ...
2509.26            1
17671.03           1
36382.23           1
168225.59          1
176087.23          1
Name: count, Length: 2682586, dtype: int64
======================================================
Unique values for column nameDest
nameDest
C1286084959    113
C985934102     109
C665576141     105
C2083562754    102
C248609774     101
              ...
M367627425       1
M1902904124      1
M242332837       1
M281573812       1
M1010678443      1
Name: count, Length: 2722362, dtype: int64
======================================================
Unique values for column oldbalanceDest
oldbalanceDest
0.00           2704388
10000000.00        615
20000000.00        219
30000000.00         86
40000000.00         31
                ...
2039554.04           1
587552.25            1
1326910.11           1
230693.29            1
851586.36            1
Name: count, Length: 3614697, dtype: int64
======================================================
Unique values for column newbalanceDest
newbalanceDest
0.00           2439433
10000000.00         53
971418.91           32
19169204.93         29
16532032.16         25
                ...
545573.72            1
7847424.27           1
1038587.91           1
1224656.68           1
2466776.70           1
Name: count, Length: 3555499, dtype: int64
======================================================
Unique values for column isFraud
isFraud
0    6354407
1       8213
Name: count, dtype: int64
======================================================
Unique values for column isFlaggedFraud
isFlaggedFraud
0    6362604
1         16
Name: count, dtype: int64
======================================================

In [ ]:
#7. Calculate the counts of isFraud and isFlaggedFraud
total_transactions = len(df)
fraud_count = df['isFraud'].sum()
flagged_fraud_count = df['isFlaggedFraud'].sum()

# Calculate the percentages
fraud_percentage = (fraud_count / total_transactions) * 100
flagged_fraud_percentage = (flagged_fraud_count / total_transactions) * 100

# Print the percentages
print(f"Percentage of isFraud: {fraud_percentage:.2f}%")
print(f"Percentage of isFlaggedFraud: {flagged_fraud_percentage:.5f}%")

Percentage of isFraud: 0.13%
Percentage of isFlaggedFraud: 0.00025%

In [ ]:
#8. For each transaction type (like PAYMENT, TRANSFER, CASH_OUT, etc.), how many transactions were fraudulent (isFraud = 1) and how many were not fraudulent (isFraud = 0)
df.groupby(['type','isFraud']).count()

                     step   amount  nameOrig  oldbalanceOrg  newbalanceOrig  \
type     isFraud
CASH_IN  0        1399284  1399284   1399284        1399284         1399284
CASH_OUT 0        2233384  2233384   2233384        2233384         2233384
         1           4116     4116      4116           4116            4116
DEBIT    0          41432    41432     41432          41432           41432
PAYMENT  0        2151495  2151495   2151495        2151495         2151495
TRANSFER 0         528812   528812    528812         528812          528812
         1           4097     4097      4097           4097            4097

                  nameDest  oldbalanceDest  newbalanceDest  isFlaggedFraud
type     isFraud
CASH_IN  0         1399284         1399284         1399284         1399284
CASH_OUT 0         2233384         2233384         2233384         2233384
         1            4116            4116            4116            4116
DEBIT    0           41432           41432           41432           41432
PAYMENT  0         2151495         2151495         2151495         2151495
TRANSFER 0          528812          528812          528812          528812
         1            4097            4097            4097            4097

**CASH_OUT** and **TRANSFER** types have relatively higher counts of fraudulent transactions compared to others, which could indicate that these types are more vulnerable to fraudulent activities.